"""Expected row counts per vtable against tests/fixtures/test_scene.blend.

Generated by running `SELECT COUNT(*) FROM <table>` for every entry in
`sqlite_master` after loading the fixture. Tables not listed here are still
covered by smoke tests, just without an exact count assertion.

If the fixture is regenerated this file must be regenerated too — keep them
in lockstep with tests/fixtures/build_fixture.py.
"""

from __future__ import annotations

EXPECTED: dict[str, int] = {
    'action_channelbags': 1,
    'action_layers': 1,
    'action_slots': 1,
    'action_strips': 1,
    'actions': 1,
    'animation_data': 1,
    'annotations': 0,
    'armatures': 1,
    'bones': 2,
    'brushes': 0,
    # bsql_columns is the per-column introspection vtable — count == sum of
    # len(COLUMNS) across every migrated vtable. Bump this every time another
    # vtable's class-attr metadata lands.
    'bsql_columns': 181,
    # bsql_tables is the introspection vtable — count == number of registered
    # tables (including itself). Keep this in lockstep with the registry; if
    # you add a new vtable, this count goes up by 1.
    'bsql_tables': 78,
    'cache_files': 0,
    'cameras': 1,
    'collection_objects': 1,
    'collections': 2,
    'constraints': 0,
    'curve_points': 3,
    'curve_splines': 1,
    'curves': 2,
    'custom_properties': 1,
    'driver_targets': 0,
    'driver_variables': 0,
    'drivers': 0,
    'fcurves': 3,
    'fonts': 1,
    'gp_drawing_attributes': 0,
    'gp_frames': 0,
    'gp_layer_groups': 0,
    'gp_layers': 0,
    'gp_points': 0,
    'gp_strokes': 0,
    'grease_pencils': 0,
    'grep': 0,
    'images': 0,
    'keyframes': 6,
    'lights': 1,
    'linestyles': 1,
    'masks': 0,
    'material_gp_settings': 0,
    'material_slots': 1,
    'materials': 1,
    'mesh_attributes': 8,
    'mesh_edges': 12,
    'mesh_loops': 24,
    'mesh_polygons': 6,
    'mesh_uvs': 0,
    'mesh_vertices': 8,
    'meshes': 1,
    'modifiers': 1,
    'movieclips': 0,
    'node_inputs': 44,
    'node_links': 3,
    'node_outputs': 3,
    'node_tree_interface': 0,
    'node_trees': 3,
    'nodes': 6,
    'objects': 7,
    'palette_colors': 120,
    'palettes': 1,
    'pose_bones': 2,
    'scene_objects': 8,
    'scenes': 2,
    'session_log': 0,
    'shape_key_blocks': 2,
    'shape_keys': 1,
    'sounds': 0,
    'texts': 1,
    'vertex_groups': 1,
    'vse_strip_color': 0,
    'vse_strip_image': 0,
    'vse_strip_movie': 0,
    'vse_strip_scene': 0,
    'vse_strip_sound': 0,
    'vse_strip_text': 0,
    'vse_strips': 0,
    'welcome': 1,
    'worlds': 1,
}
